import type { Config } from 'tailwindcss'

export default {
  content: [
    './components/**/*.{vue,js,ts}',
    './layouts/**/*.vue',
    './pages/**/*.vue',
    './composables/**/*.{js,ts}',
    './plugins/**/*.{js,ts}',
    './app.vue',
  ],
  theme: {
    extend: {
      colors: {
        'on-tertiary-fixed-variant': '#454747',
        'tertiary-container': '#101212',
        'primary-fixed': '#e5e2e1',
        outline: {
          DEFAULT: '#8e9192',
          variant: '#444748',
        },
        'surface-variant': '#353535',
        'surface-container-highest': '#353535',
        'on-tertiary-container': '#7c7d7e',
        'secondary-fixed-dim': '#e9c176',
        surface: {
          DEFAULT: '#131313',
          dim: '#131313',
          bright: '#393939',
          variant: '#353535',
          container: '#20201f',
          'container-low': '#1c1b1b',
          'container-high': '#2a2a2a',
          'container-highest': '#353535',
          'container-lowest': '#0e0e0e',
        },
        'on-surface-variant': '#c4c7c7',
        'on-primary-container': '#7e7d7d',
        'inverse-on-surface': '#313030',
        'secondary-fixed': '#ffdea5',
        'on-secondary-container': '#dab36a',
        primary: {
          DEFAULT: '#c8c6c5',
          container: '#121212',
          fixed: '#e5e2e1',
          'fixed-dim': '#c8c6c5',
        },
        'on-primary-fixed': '#1c1b1b',
        secondary: {
          DEFAULT: '#e9c176',
          container: '#604403',
          fixed: '#ffdea5',
          'fixed-dim': '#e9c176',
        },
        tertiary: '#c6c6c7',
        'on-surface': '#e5e2e1',
        'error-container': '#93000a',
        'on-tertiary-fixed': '#1a1c1c',
        'tertiary-fixed-dim': '#c6c6c7',
        'on-error': '#690005',
        'on-secondary': '#412d00',
        'on-tertiary': '#2f3131',
        'on-primary': '#313030',
        'surface-tint': '#c8c6c5',
        'inverse-primary': '#5f5e5e',
        'on-secondary-fixed-variant': '#5d4201',
        'on-error-container': '#ffdad6',
        'on-background': '#e5e2e1',
        'on-secondary-fixed': '#261900',
        background: '#131313',
        'on-primary-fixed-variant': '#474646',
        'inverse-surface': '#e5e2e1',
        'tertiary-fixed': '#e2e2e2',
        error: '#ffb4ab',
        // Legacy aliases (pre-redesign admin + product-detail pages still use these) mapped to the M3 palette
        gold: { DEFAULT: '#e9c176', light: '#ffdea5', dark: '#604403' },
        dark: { bg: '#131313', surface: '#1c1b1b', border: '#444748', lighter: '#353535' },
      },
      fontFamily: {
        sans: ['Hanken Grotesk', 'sans-serif'],
        display: ['EB Garamond', 'serif'],
        'headline-sm': ['Hanken Grotesk'],
        'headline-md': ['EB Garamond'],
        'display-lg': ['EB Garamond'],
        'display-lg-mobile': ['EB Garamond'],
        'headline-lg': ['EB Garamond'],
        'body-lg': ['Hanken Grotesk'],
        'body-md': ['Hanken Grotesk'],
        'body-sm': ['Hanken Grotesk'],
        'label-md': ['Hanken Grotesk'],
      },
      fontSize: {
        'display-lg': ['48px', { lineHeight: '1.1', letterSpacing: '-0.02em', fontWeight: '400' }],
        'display-lg-mobile': ['32px', { lineHeight: '1.2', letterSpacing: '-0.01em', fontWeight: '400' }],
        'headline-lg': ['40px', { lineHeight: '1.15', fontWeight: '400' }],
        'headline-md': ['32px', { lineHeight: '1.2', fontWeight: '400' }],
        'headline-sm': ['20px', { lineHeight: '1.4', letterSpacing: '0.05em', fontWeight: '500' }],
        'body-lg': ['18px', { lineHeight: '1.6', fontWeight: '300' }],
        'body-md': ['16px', { lineHeight: '1.6', fontWeight: '400' }],
        'body-sm': ['14px', { lineHeight: '1.5', fontWeight: '400' }],
        'caption': ['11px', { lineHeight: '1.4', letterSpacing: '0.08em', fontWeight: '500' }],
        'label-md': ['12px', { lineHeight: '1', letterSpacing: '0.1em', fontWeight: '600' }],
      },
      spacing: {
        gutter: '32px',
        'section-gap': '128px',
        'margin-mobile': '24px',
        'margin-desktop': '64px',
        'container-max': '1280px',
        unit: '8px',
      },
      borderRadius: {
        DEFAULT: '0px',
        lg: '0px',
        xl: '0px',
        '2xl': '0px',
        full: '9999px',
      },
    },
  },
  plugins: [],
} satisfies Config
